ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("ProyectoWebApp.urls")),

    path("servicios/", include("servicios.urls")),

    path("blog/", include("blog.urls")),
 
    path("contacto/", include("contacto.urls")),

    path("tienda/", include("TiendaU.urls")),

    path("carro/", include("carro.urls")),

    path("autenticacion/", include("autenticacion.urls")),
    
    path("pedidos/", include("pedidos.urls")),
    
   

    

]

TiendaU/urls.py
from django.urls import path

from TiendaU import views


urlpatterns = [

    path("", views.tienda, name="Tienda"), 
    path("categoria/<int:categoria_id>/", views.categoria, name="Categoria"),
    
]
  

blog/urls.py
from django.urls import path

from . import views          #el punto significa que me dirige  a la raiz de dónde estoy 


urlpatterns = [
    path("", views.blog, name="Blog"),
    path("categoria/<int:categoria_id>/", views.categoria, name="categoria"),  #"<categoria_id>/": los "<>" es para especificar que es un parametro       (7:45 video41)
]                                                                                                       #con parametros me refiero a que cuando pongas un valor (en este caso un 1 o 2) , por ejem: http://localhost:8000/blog/categoria/1                                        
                                                                                                        # y luego ese valor irá a la funcion "def categoria" de views.py   

carro/urls.py
from django.urls import path

from carro import views

                    #DATITO
app_name="carro"  # es para que no haya colision entre "name" (16:00 video 56 )

urlpatterns = [

    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"), 
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/<int:producto_id>/", views.limpiar_carro, name="limpiar"),
    
]
  

TiendaU/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True) 
    updated=models.DateTimeField(auto_now_add=True) 
     
    class Meta:
        verbose_name="categoria"
        verbose_name_plural="categorias"

    def __str__(self):
        return self.nombre

class Producto(models.Model):    
    nombre=models.CharField(max_length=50)
    imagen=models.ImageField(upload_to="Tienda", null=True, blank=True)                    # el "upload_to es para tener que la imagen se guarde en /media/servicios"
    precio=models.FloatField() 
    disponibilidad=models.BooleanField(default=True)

        
    categorias=models.ForeignKey(Categoria, on_delete=models.CASCADE)                  #relación 1 a varios

    created=models.DateTimeField(auto_now_add=True) 
    updated=models.DateTimeField(auto_now_add=True) 
     
    class Meta:
        verbose_name="Producto"
        verbose_name_plural="Productos"

carro/models.py
from django.db import models

# Create your models here.

TiendaU/views.py
from django.shortcuts import render
from TiendaU.models import Producto, Categoria
# Create your views here.


def tienda (request):

    Tienda=Producto.objects.all()

    return render(request, "TiendaT/tienda.html", {"Tiendas":Tienda})

 

def categoria(request, categoria_id):               

    categoria=Categoria.objects.get(id=categoria_id)
    
    Tienda=Producto.objects.filter(categorias=categoria_id)  #si pongo esto "categorias=categoria_id" igual funcionaría
                                                                   #        categorias_id=categoria        <- con esto igual funciona
                                                                   #        categorias_id=categoria_id     <-tambien funciona
    return render(request, "TiendaT/categorias.html", {"categoria":categoria,"Tiendas":Tienda})

carro/views.py
from django.shortcuts import render
from .carro import Carro
from TiendaU.models import Producto
from django.shortcuts import redirect

# Create your views here.

def agregar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)       #  -->                      <Producto: Teclado inalámbrico>      
                                                      #Producto.objects.all() --> [<Producto: Teclado inalámbrico>, <Producto: Teclado con cable>, <Producto: teclado simple>, <Producto: Raton gamer>, <Producto: Raton inalámbrico>]
                                                                               #    [<Producto: Producto object (1)>, <Producto: Producto object (2)>, <Producto: Producto object (3)>, <Producto: Producto object (4)>, <Producto: Producto object (5)>]
    carro.agregar(producto)
    return redirect("Tienda")


def eliminar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)      
                                                      
    carro.eliminar(producto)

    return redirect("Tienda")


def restar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)      
                                                      
    carro.restar_producto(producto)

    return redirect("Tienda")


def limpiar_carro(request, producto_id):

    carro=Carro(request)

    carro.limpiar_carro()

    return redirect("Tienda")

TiendaU/templates/carro/widget.html
<table class="table table-bordered" style="color: white;">

    <thead>
        <tr>


            <th colspan="3" class="text-center">  

                Carro compras
            
            
            </th>
        
        </tr>

        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Producto </th>
        </tr>

    </thead>

    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}    

                <tr class="text-center">    
                    
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        
                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>   <!--Leer linea 4 de carro/urls.py -->
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a><br/>  <!--El "<br/> es para hacer un salto de línea -->

                        {{value.precio}} $

                    </td>

                    

                </tr>

            {% endfor %}

        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center"> <!-- esta "class" es de boostrap-->

                        sin productos
                    </div>
                
                </td>
            
            </tr>

        {% endif %}
    
    </tbody>

    <tfoot>
            <tr>

                <td  colspan="3">

                Total: {{importe_total_carro}} $

                </td>
            
            
            </tr>

            {% if request.session.carro.items %}  <!-- si el usuario logeado tiene articulos en el carror-->

            <tr>

                <td  colspan="3" style="text-align: center;">

                    <a href="../pedidos" class="btn btn-success">Hacer Pedidos</a>

                </td>
            
            
            </tr>

            {% endif %}
    </tfoot>



</table>